server:
  port: 8081
spring:
  application:
    name: gateway-predicate
  profiles:
    active: path_query



---

spring:
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: https://www.baidu.com
        predicates:
        - Path=/csdn
  profiles: path_route


---
spring:
  cloud:
    gateway:
      routes:
      - id: query_route
        uri: https://www.baidu.com
        predicates:
        - Query=gateway
  profiles: path_query

---
spring:
  cloud:
    gateway:
      routes:
      - id: header_route
        uri: https://www.baidu.com
        predicates:
        - Header=X-Request-Id,\d+   #curl http://localhost:8081 -H "X-Request-Id:88"
  profiles: path_header


---
spring:
  cloud:
    gateway:
      routes:
      - id: cookie_route
        uri: https://www.baidu.com
        predicates:
        - Cookie=gateway,test
  profiles: path_cookie #curl http://localhost:8081 --cookie "gateway=test"

---
spring:
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: https://www.baidu.com
        predicates:
        - Host=**.baidu.com
  profiles: path_host   #curl http://localhost:8081 -H "Host: md.baidu.com"